"""Updating Execution with error message

Revision ID: 08595cee4245
Revises: 41a7ef227a90
Create Date: 2026-09-20 12:42:32.823805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08595cee4245'
down_revision: Union[str, Sequence[str], None] = '41a7ef227a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'error_message')
    # ### end Alembic commands ###
