"""Adding Retry Attempts and Error Handling

Revision ID: 41a7ef227a90
Revises: ac5e642162ec
Create Date: 2026-09-16 21:26:23.786501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a7ef227a90'
down_revision: Union[str, Sequence[str], None] = 'ac5e642162ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('retry_attempts', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.alter_column('executions', 'output',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('executions', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('executions', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('executions', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('executions', 'provider_response_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executions', 'provider_response_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('executions', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('executions', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('executions', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('executions', 'output',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('executions', 'retry_attempts')
    # ### end Alembic commands ###
