"""add execution cost_usd

Revision ID: 950e42646281
Revises: 08595cee4245
Create Date: 2026-10-04 15:38:47.760879

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '950e42646281'
down_revision: str | Sequence[str] | None = '08595cee4245'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'cost_usd')
    # ### end Alembic commands ###
